// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEOPKHXqW6ldQLOk0gSybntbSsdIqNgAY',
    appId: '1:810073043255:web:ba18847d91bb922b23eab2',
    messagingSenderId: '810073043255',
    projectId: 'oweflow-80c7a',
    authDomain: 'oweflow-80c7a.firebaseapp.com',
    storageBucket: 'oweflow-80c7a.appspot.com',
    measurementId: 'G-9ZCPV7Y8VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF4jIMVsfH1OS79uDqjtchqBw685ZH5G0',
    appId: '1:810073043255:android:aca230c7627496ed23eab2',
    messagingSenderId: '810073043255',
    projectId: 'oweflow-80c7a',
    storageBucket: 'oweflow-80c7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHwyx6oc5IXpuS2RJa-MRPxg_PkUdjXwc',
    appId: '1:810073043255:ios:70abdabee986a36e23eab2',
    messagingSenderId: '810073043255',
    projectId: 'oweflow-80c7a',
    storageBucket: 'oweflow-80c7a.appspot.com',
    iosBundleId: 'com.example.oweflow',
  );
}
